# inherit from the proprietary version
-include vendor/INSIGNIA/INSIGNIA/BoardConfigVendor.mk
#include device/INSIGNIA/INSIGNIA/boot.mk

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a7


ARCH_ARM_HAVE_TLS_REGISTER := true
#TARGET_KMODULES := true
TARGET_BOARD_PLATFORM := mt6589
#TARGET_OTA_ASSERT_DEVICE := INSIGNIA 5,INSIGNIA
#TARGET_BOOTLOADER_BOARD_NAME := INSIGNIA/unknown (?)

#########        KERNEL        #########
## For build kernel
#TARGET_KERNEL_SOURCE := kernel/INSIGNIA/kernel
#TARGET_KERNEL_CONFIG := ProjectConfig.mk kernel/INSIGNIA/kernel-name/arch/arm/configs/cyanogenmod_device-name_deconfig
#BOARD_USES_UBOOT := true
BOARD_CUSTOM_BOOTIMG_MK := device/INSIGNIA/INSIGNIA/boot.mk
TARGET_PREBUILT_KERNEL := device/INSIGNIA/INSIGNIA/kernel
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/mt_usb/gadget/lun%d/file
#TARGET_RAMDISK_KERNEL := device/INSIGNIA/INSIGNIA/rootdir
INSTALLED_RAMDISK_TARGET := device/INSIGNIA/INSIGNIA/rootdir
#########         END         #########

TARGET_ARCH_LOWMEM := true
BOARD_LDPI_RECOVERY := true
TARGET_NO_BOOTLOADER := true
#TARGET_NO_RECOVERY := true //if true don't work
TARGET_NO_RADIOIMAGE := true
#TARGET_NO_FACTORYIMAGE := true
#TARGET_NO_BOOTIMAGE := true
#TARGET_NO_KERNEL := true

BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/INSIGNIA/INSIGNIA/bluetooth
BOARD_HAVE_BLUETOOTH := true

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
#BOARD_NAND_PAGE_SIZE := 2048 -s 64
#BOARD_FORCE_RAMDISK_ADDRESS := 
#BOARD_MKBOOTIMG_ARGS := --ramidsk_offset2048

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 6291456
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 6291456
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 891289600
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824
TARGET_USERIMAGES_USE_EXT4:=true
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true
#BOARD_CACHEIMAGE_PARTITION_SIZE := 132120576
#BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 131072

BOARD_HAS_NO_SELECT_BUTTON := true

# for migrate build system
# temporarily open this two options
#HAVE_HTC_AUDIO_DRIVER := true
BOARD_USES_GENERIC_AUDIO := true
USE_CAMERA_STUB := true
TARGET_CPU_SMP := true
BOARD_MTK_LIBSENSORS_NAME :=
BOARD_MTK_LIB_SENSOR :=
USE_OPENGL_RENDERER := true
BOARD_USES_MTK_AUDIO := true

BOARD_EGL_CFG := device/INSIGNIA/INSIGNIA/egl.cfg

#BOARD_MTK_LIBSENSORS_NAME := hardware/mt/sensors/sensor/hwmsen_custom.h
#BOARD_MTK_LIB_SENSOR := hardware/mt

BOARD_AGPS_SUPL_LIBRARIES := true
BOARD_GPS_LIBRARIES := true
BOARD_WPA_SUPPLICANT_DRIVER := WEXT
BOARD_P2P_SUPPLICANT_DRIVER := NL80211
HAVE_CUSTOM_WIFI_DRIVER_2 := true
HAVE_INTERNAL_WPA_SUPPLICANT_CONF := true
HAVE_CUSTOM_WIFI_HAL := mediatek
WPA_SUPPLICANT_VERSION := VER_0_6_X
P2P_SUPPLICANT_VERSION := VER_0_8_X

#ifeq ($(strip $(MTK_NAND_PAGE_SIZE)), 4K)
#  BOARD_NAND_PAGE_SIZE := 4096 -s 128
#else
#  BOARD_NAND_PAGE_SIZE := 2048 -s 64   # default 2K
#endif

#####   deodex   #####
WITH_DEXPREOPT := false
#####  false=on  #####

# include all config files
include device/INSIGNIA/INSIGNIA/configs/*.mk

#BOARD_CAMERA_USE_GETBUFFERINFO := true
TARGET_PREBUILT_LIBCAMERA := true
TARGET_CAMERA_SENSOR_MP_SIZE := 8
